### ISSUE TITLE
Update NLog to latest version, instead of BETA 

### ISSUE THREAD

**Issue by snakefoot** [Radarr/RadarrAPI#6]
https://github.com/Radarr/RadarrAPI.Update/blob/1065bee945b61b06f7adaff0f5677fdeae038b93/RadarrAPI/RadarrAPI.csproj#L11-L12

NLog 4.5.0 (And newer) supports NetCore https://www.nuget.org/packages/NLog/ (NLog 5.0.0-BETA has been pulled)

**Comment by AeonLucid** [comment]
Done.
